config/routes.rb
Rails.application.routes.draw do

  root 'application#home'

  resources :track_times
  resources :drivers
  resources :tracks


  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'

  get '/signout', to: 'sessions#destroy'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
    has_secure_password
    has_many :tracktimes
    has_many :tracks, through: :tracktimes 
end

app/models/track.rb
class Track < ApplicationRecord
    has_many :track_times
    has_many :drivers, through: :track_times
    
end

app/models/track_time.rb
class TrackTime < ApplicationRecord
  belongs_to :track
  belongs_to :driver
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :authorize, :current_driver, :racemaster


    def home 
    end

    #set this to admin 
    def show_time

    end

    def authorize
        redirect_to '/signin' unless current_driver
    end

    #set up current driver 
    def current_driver 
        @driver ||= Driver.find(session[:driver_id]) if session[:driver_id]
        
    end

    def racemaster
        current_driver.racemaster
    end





end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController

    
    def index
        @drivers = Driver.all 
    end
    

    def new 
        @driver = Driver.new
    end


    def create 
        @driver = Driver.create(driver_params)
        redirect_to driver_path(@driver)
    end
    

    def show 
        find_driver
    end


    def edit 
        find_driver
    end

    def update 
        find_driver
        @driver.update(driver_params)
        redirect_to driver_path(@driver)
    end

  




    private

    def driver_params
        params.require(:driver).permit(:name, :password, :car, :racemaster)
    end

    def find_driver
        @driver = Driver.find(params[:id])
        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


    def new 
    end

    def create
        @driver = Driver.find_by(name: params[:name])
        if @driver && @driver.authenticate(params[:password])
            session[:driver_id] = @driver.id 
            redirect_to driver_path(@driver)
        else
            render :new
        end
    end


    def destroy
        session.clear
        redirect_to root_path
    end

  
end

app/controllers/track_times_controller.rb
class TrackTimesController < ApplicationController

    def create 
        @tracktime = TrackTime.create(tracktime_params)
        redirect_to  driver_path(@driver)
    end



    private 

    def tracktime_params
        params.require(:tracktime).permit(:driver_id, :track_id, :laptime)
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

   
   def index
   end
   
    def new 
        @track = Track.new
    end

    def create 
        @track = Track.create(track_params)
        # binding.pry
        redirect_to track_path(@track)
    end

    def show
        @track = Track.find(params[:id])
    end

    def edit 
        @track = Track.find(params[:id])
    end

    def update 
        @track = Track.find(params[:id])
        @track.update(track_params)
        redirect_to track_path(@track)
    end


    def destroy
        @track = Track.find(params[:id])
        @track.delete
        render :index
    end


    private 

    def track_params
        params.require(:track).permit(:name, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/track_times_helper.rb
module TrackTimesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/application/home.html.erb
<h1>This is is the Home Page</h1>

app/views/drivers/_driverform.html.erb
<%= form_for @driver do |f|%>
    <%= f.label :name%>
    <%= f.text_field :name%>

    <%= f.label :password%>
    <%= f.password_field :password%>

    <%= f.label :car %>
    <%= f.text_field :car %><br>

    <%= f.label :racemaster%>
    <%= f.text_field :racemaster%>

    <%=f.submit %>

<% end %>

app/views/drivers/edit.html.erb
<h1>Edit the driver: </h1>

<%= render 'driverform' %>

app/views/drivers/index.html.erb
<h1>Here is everyone  else </h1>

<ul>
<%# add in their lap times when made %>
<%Driver.all.each do |driver| %>
    <li><%= link_to "#{driver.name}", driver %></li>
<% end %>

</ul>

app/views/drivers/new.html.erb
<h1>Welcome New Driver!!!</h1>


<%= render 'driverform' %>

app/views/drivers/show.html.erb
<h1>Welcome <%= @driver.name %></h1>






<%# insert track options here...  %>
<%= link_to " All Tracks", tracks_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= link_to "Sign Out", signout_path, method: :delete %>
    <%= link_to "Sign In", signin_path%>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tracks/_form.html.erb
<%= form_for @track do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :location %>
  <%= f.text_field :location %>
   
  <%= f.submit %>
<% end %> 

app/views/tracks/edit.html.erb
<h2>Lets change the things about this track </h2>


<%= render 'form' %>

app/views/tracks/index.html.erb
<h2>Here are all the tracks</h2>

<ul>
<% Track.all.each do |track| %>
   <li><%= link_to "#{track.name}", track %></li>
<% end %>
</ul>

app/views/tracks/new.html.erb
<h1>Set up New Track </h1>

<%= render 'form'%>

app/views/tracks/show.html.erb
<h1> Welcome To The <%=@track.name%> In <%=@track.location%>  </h1> 


<%# Lets show the lap times of the racers...  %>

<%= button_to "Delete", track_path(@track), method: :delete %>

<%# add button for adding track time with user.id %>

<% if racemaster%>
   <%= link_to "Edit Track", edit_track_path(@track)%>
<% end %>